import Head from "next/head";
import GradePanel from "../components/GradePanel";
import { trpc } from "../utils/trpc";

export default function Home() {
  const hello = trpc.hello.useQuery({ text: "client " });

  if (!hello.data) {
    return <div>Loading ...</div>;
  }
  return (
    <>
      <Head>
        <title>Mood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-center py-4">
          Hello, Andre =)
          <br />
          <strong>how was your day, today?</strong>
        </h1>
        <p>{hello.data.greeting}</p>
        <div className="flex justify-items-center ml-auto mr-auto max-w-xl">
          <GradePanel />
        </div>
      </main>
    </>
  );
}
