import Head from 'next/head'
import Button from '../components/Button'
import GradePanel from '../components/GradePanel'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mood</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <h1 className='text-center py-4'>Hello, Andre =)<br /><strong>how was your day, today?</strong></h1>
        <GradePanel />
      </main>
    </>
  )
}
